---
title: 'Cluster #4'
author: "Liam Tolbert"
date: "2022-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#install.packages("plyr")
library(plyr)
library(pROC)
library(plotly)
library(randomForest)
library(mltools)
library(rio)
library(caret)
library(ROCR)
library(tidyverse)
library(data.table)
library(rpart)
#install.packages("pscyh")
library(psych)
library(pROC)
#install.packages("rpart.plot")
library(rpart.plot)
#install.packages("rattle")
library(rattle)
```


```{r}
clusterdata <- read.csv("cluster_4_data.csv")
clusterdata <- clusterdata %>% select(-c(clusterNum, state, county, obesrateLevel))
#clusterdata <- one_hot(as.data.table(clusterdata),cols="obesrateLevel",sparsifyNAs = TRUE,naCols = FALSE,dropCols = TRUE,dropUnusedLevels = TRUE)

```


Create test, tune and training sets 
```{r}
part_index_1 <- createDataPartition(clusterdata$obesrate,
                                           times=1,
                                           p = 0.70,
                                           groups=1,
                                           list=FALSE)

train <- clusterdata[part_index_1,]
test <- clusterdata[-part_index_1, ]

```

Calculate the initial mtry level 
```{r}
mytry_tune <- function(x){
  xx <- dim(x)[2]-1
  sqrt(xx)
}

mytry_tune(clusterdata)
```

```{r}
cluster_RF = randomForest(obesrate~., train, ntree = 500,
                            mtry = 2,            
                            replace = TRUE,      
                            sampsize = 100,      
                            nodesize = 5,        
                            importance = TRUE,   
                            proximity = FALSE,    
                            norm.votes = TRUE,   
                            do.trace = TRUE,     
                            keep.forest = TRUE,  
                            keep.inbag = TRUE)   
```

```{r}
View(as.data.frame(cluster_RF$importance))

cluster4 = predict(cluster_RF,newdata=test)
mean((cluster4-test$obesrate)^2)
mean((mean(test$obesrate)-test$obesrate)^2)
mean((mean(train$obesrate)-test$obesrate)^2)
```
