---
title: "Nathan"
author: "Nathan, Alex, Caesar, Liam"
date: "2022-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#install.packages("plyr")
library(plyr)
library(pROC)
library(plotly)
library(randomForest)
library(mltools)
library(rio)
library(caret)
library(ROCR)
library(tidyverse)
library(data.table)
library(rpart)
#install.packages("pscyh")
library(psych)
library(pROC)
#install.packages("rpart.plot")
library(rpart.plot)
#install.packages("rattle")
library(rattle)
```


```{r}
cluster1 <- read.csv("cluster_1_data.csv")
cluster1 <- cluster1 %>% select(-c("clusterNum", "state", "county", "obesrateLevel"))
```


Create test, tune and training sets 
```{r}
# 85% train 15% for tune and test, try to give more data for random forest training
set.seed(2001)
part_index_1 <- createDataPartition(cluster1$obesrate,
                                           times=1,
                                           p = 0.85,
                                           groups=1,
                                           list=FALSE)
train <- cluster1[part_index_1,]
test <- cluster1[-part_index_1, ]
```

Calculate the initial mtry level 
```{r}
mytry_tune <- function(x){
  xx <- dim(x)[2]-1
  sqrt(xx)
}
mytry_tune(cluster1) # 2.236068 -> 2
```

```{r}
set.seed(2001)
cluster1_RF = randomForest(obesrate~., train, ntree = 500,
                            mtry = 2,            
                            replace = TRUE,      
                            sampsize = 100,      
                            nodesize = 5,        
                            importance = TRUE,   
                            proximity = FALSE,    
                            norm.votes = TRUE,   
                            do.trace = TRUE,     
                            keep.forest = TRUE,  
                            keep.inbag = TRUE)   
```

```{r}
View(as.data.frame(cluster1_RF$importance))

# Diabetes was the most important in predicting the obesity rate which makes sense since these would appear to be highly correlated variables at first glance.
```

Testing and optimizing by picking the most appropriate mtry, node size and ntree.
```{r}
yhat.cluster1 = predict(cluster1_RF,newdata=test)
mean((yhat.cluster1-test$obesrate)^2)
mean((mean(test$obesrate)-test$obesrate)^2)
mean((mean(train$obesrate)-test$obesrate)^2)
```